import{S as m,i as c}from"./assets/vendor-0fc460d7.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function e(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=e(r);fetch(r.href,o)}})();const p="45339171-09ca964bcb6303fe660a59875",y="https://pixabay.com/api/";async function h(t,n=1){try{const e=await fetch(`${y}?key=${p}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=40&page=${n}`);if(!e.ok)throw new Error("Failed to fetch images");return await e.json()}catch(e){throw console.error("Error fetching images:",e),e}}const l=document.querySelector(".gallery");let i;function g(t){const n=t.map(e=>`<div class="photo-card">
              <a href="${e.largeImageURL}">
                <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
              </a>
              <div class="info">
                <p><b>Likes:</b> ${e.likes}</p>
                <p><b>Views:</b> ${e.views}</p>
                <p><b>Comments:</b> ${e.comments}</p>
                <p><b>Downloads:</b> ${e.downloads}</p>
              </div>
            </div>`).join("");l.insertAdjacentHTML("beforeend",n),i?i.refresh():i=new m(".gallery a")}function b(){l.innerHTML=""}const w=document.querySelector("#search-form"),u=document.querySelector("#loader");let d=1,f="";w.addEventListener("submit",L);function L(t){t.preventDefault();const n=t.currentTarget.elements.searchQuery.value.trim();if(n===""){c.warning({title:"Warning",message:"Please enter a search term!"});return}b(),d=1,f=n,$()}async function $(){v();try{const t=await h(f,d);t.hits.length===0?c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}):g(t.hits)}catch{c.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{P()}}function v(){u.style.display="block"}function P(){u.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
